### ISSUE TITLE
bug: auto-resize code editor on window size change.

### ISSUE THREAD

**Issue by mikeal** [ipfs-shipyard/proto.school#1]

**Comment by olizilla** [comment]
Big Trouble in Little Monaco. Calling `this.editor.layout()` doesn't seem to be working. Nether does `{automaticLayout: true}` in the editor options.

**Comment by olizilla** [comment]
huh. the docs for `vue-monaco-editor` are wrong. The option for options is `options`.

**Comment by terichadbourne** [comment]
@olizilla @mikeal Should this issue still be open or has it been resolved to your satisfaction?

**Comment by mikeal** [comment]
This works great now, and is even better than originally spec'd :)
