### ISSUE TITLE
Extract IPLD Explorer from webui

### ISSUE THREAD

**Issue by olizilla** [ipfs-shipyard/proto.school#10]
Standalone IPLD Explorer is here:
https://ipfs.io/ipfs/QmYJETQ15RAnKXoJxqpXzcvQ2DuQA35UHwJBTjTPCSs9Ky

repo:
https://github.com/ipfs-shipyard/ipld-explorer

I'd like to deploy it to https://explorer.ipld.io to make the url more memorable
https://github.com/ipfs-shipyard/ipld-explorer/issues/2

If you want to link to hide the header, just `?embed=true` to the url, like:

https://ipfs.io/ipfs/QmYJETQ15RAnKXoJxqpXzcvQ2DuQA35UHwJBTjTPCSs9Ky/?embed=true#/explore/QmTxRvftPnKeR7iJfeVpfsGCYEwZ92ot9zrTksAWUACTs7

To link straight to a specific CID or path, prefix it with:
```
https://ipfs.io/ipfs/QmYJETQ15RAnKXoJxqpXzcvQ2DuQA35UHwJBTjTPCSs9Ky/?embed=true#/explore/
```

**Comment by olizilla** [comment]
Also of note, right now this uses https://github.com/tableflip/window.ipfs-fallback to select which ipfs instance to use, and, as it's still got it's webui hat on, it'll try and use `window.ipfs` from companion, and if it's not present, it'll fallback to js-ipfs-api, and try and connect to a daemon on the default port...

It'd be great to get everyone to install ipfs companion, but for the workshop, this might add additional friction, so I'll update window.ipfs-fallback to allow a 3 step look up that bottoms out in a local `js-ipfs` node.

**Comment by olizilla** [comment]
This is done in #27  We have fallback to js-ipfs in https://github.com/ipfs-shipyard/ipld-explorer/pull/5 and that is deployed and proto.school is updated to use that version of the app. Ideally we'd get `explore.ipld.io` as the dnslink'd domain but that is pending, so we're rolling with the CID address for now.

https://ipfs.io/ipfs/QmYJETQ15RAnKXoJxqpXzcvQ2DuQA35UHwJBTjTPCSs9Ky

**Comment by hacdias** [comment]
Plans to use it directly on WebUI?

**Comment by olizilla** [comment]
@hacdias pls raise an issue with your thoughts and suggestions on the the ipld-explorer repo. https://github.com/ipfs-shipyard/ipld-explorer
