### ISSUE TITLE
Feedback basic lessons

### ISSUE THREAD

**Issue by vmx** [ipfs-shipyard/proto.school#20]
I went through the basic lessons.

In lesson 2 it wasn't clear to me what I should actually do. I tried adding this line:

```javascript
return {bar: {'/': cid.toBaseEncodedString()}}
```

But I got `Did not return a valid CID instance. ` So I guess I need to return a CID. I then did

```javascript
  const link = {bar: {'/': cid.toBaseEncodedString()}}
  return await ipfs.dag.put(link)
```

Which was correct. Though it could also have been that you need to create a CID somehow.

Lesson 3:

The last sentence has a typo "traversing" and isn't really a sentence (but I figured out what do to :):

> For the next lesson, take the linked object to just stored and return the value of test by travesing through the links.

**Comment by mikeal** [comment]
Great feedback! Will work to make this clearer.
