### ISSUE TITLE
vue-monaco-editor loading monaco editor from alipayobjects.com

### ISSUE THREAD

**Issue by olizilla** [ipfs-shipyard/proto.school#29]
vue-monaco-editor lasy loads the editor code from a CDN called alipayobjects.com

<img width="758" alt="screenshot 2018-07-30 14 39 13" src="https://user-images.githubusercontent.com/58871/43400727-5cf9a61a-9406-11e8-8c27-a9d060691ac7.png">

This might weird people out. Combined with the fact that vue-monaco-editor says [it's unmaintained](https://github.com/matt-oconnell/vue-monaco-editor#vue-monaco-editor) we should replace that dependency.

**Comment by olizilla** [comment]
We could use the `srcPath` property to point at a different cdn in the short term, but ideally all the code would be included in the js bundle published to IPFS, which we could get with some webpacking
https://github.com/matt-oconnell/vue-monaco-editor#webpack-use

**Comment by mikeal** [comment]
there's an option to not load it remotely and include it in the bundle, it's just going to increase the bundle size even more :(

**Comment by olizilla** [comment]
Is ok. We can teach webpack to split the bundle on dynamic imports. That's what IPLD Explorer is doing for the graph lib and for the window.ipfs -> js-ipfs-api -> js-ipfs multi-fallback loading.

**Comment by olizilla** [comment]
My concern was more about the rando requests and how peeps at dweb might be somewhat more privacy conscious then the average.

**Comment by lgierth** [comment]
> there's an option to not load it remotely and include it in the bundle, it's just going to increase the bundle size even more :(

Yeah but proto.school would offline :)

**Comment by lgierth** [comment]
Just imagine internet at DWeb Summit breaks down while your showing proto.school to someone :)

**Comment by mikeal** [comment]
> Yeah but proto.school would work offline :)

Yes, except for IPLD Explorer :(

**Comment by mikeal** [comment]
FYI, webpack configuration is in vue.config.js :)

**Comment by olizilla** [comment]
I might be daring to dream but I think we can have it all. 

IPLD explorer loads all its assets from the same root CID, so if you've got companion installed, and we update proto.school to bundle all the deps and check for `window.ipfs` then both the exercises and the explorer would use the same IPFS repo, and the whole thing could work without http.

**Comment by olizilla** [comment]
To get #25 working nicely I need a `editor.layout()` to work, so I'm gonna try updating the editor and loading it locally.

**Comment by mikeal** [comment]
I had it doing this reliably a while back, I was working on a branch than
make the editor resizable but once I had it working, resizing the editor by
hand was not that useful. If you merge where it is I can poke at it in the
morning.

**Comment by olizilla** [comment]
The `autoLayout` option is working now in #28 and that PR fixes this issue too. Please take a look when you get a moment.
