### ISSUE TITLE
gh-pages branch is gone

### ISSUE THREAD

**Issue by lgierth** [ipfs-shipyard/proto.school#46]
The branch is gone, so https://proto.school is a 404 now

**Comment by jbenet** [comment]
Yeah just saw that now too

**Comment by mikeal** [comment]
The branch was re-created when I merged Steve's PR this morning.

Someone, or a bot, must have deleted the remote branch. Are there any github logs that might tell use who/what did this?

**Comment by lgierth** [comment]
> - diasdavid – repo.pages_destroy
> - Deleted GitHub Pages site in ipfs-shipyard/proto.school
> - United States 3 days ago

cc @diasdavid what was up there?

**Comment by mikeal** [comment]
😱

**Comment by diasdavid** [comment]
oh damn it. My bad, totally thought that it was being deployed to IPFS now. (I do have a habit of cleaning branches that are old and have been merged or PRs that were fully closed)

**Comment by diasdavid** [comment]
My bad, I'm sorry! Totally thought that it was being deployed to IPFS now (why isn't it?). (I do have a habit of cleaning branches that are old and have been merged or PRs that were fully closed)

**Comment by mikeal** [comment]
@diasdavid expedience :) we pushed off any hosting migrations until after DWeb, see #18
