### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by mikeal** [ipfs-shipyard/proto.school#52]
We need a cool logo for ProtoSchool :)

One of the most successful aspects of the NodeSchool visual design was the logo that allowed the community to create dozens of derivative logos for their local chapters.

Basic | Hex | International Day
--- | --- | --- 
<img width="796" alt="screen shot 2018-09-05 at 2 21 29 pm" src="https://user-images.githubusercontent.com/579/45121822-1b965000-b117-11e8-931c-ba29ae2d9126.png"> | ![logo](https://user-images.githubusercontent.com/579/45121540-4e8c1400-b116-11e8-931d-9d7b7b046010.png) | ![international-day-logo](https://user-images.githubusercontent.com/579/45121470-18e72b00-b116-11e8-9056-14c3c040b35a.png)

A full [list of local chapter logos is in their "hexdex"](https://nodeschool.io/hexdex.html).

Here's some of my favorite.

Seoul | Tokyo | Lisbon
--- | --- | --- 
![nodeschool-seoul](https://user-images.githubusercontent.com/579/45121908-4da7b200-b117-11e8-88d6-b572f7841327.png) | ![nodeschool-tokyo](https://user-images.githubusercontent.com/579/45121974-729c2500-b117-11e8-9a16-47dbc905b795.png) | <img width="400" alt="screen shot 2018-09-05 at 2 21 29 pm" src="https://user-images.githubusercontent.com/579/45121981-76c84280-b117-11e8-9c76-fea966615d13.png">
San Jose | Los Angeles | Cleveland
![nodeschool-costarica](https://user-images.githubusercontent.com/579/45122152-e9392280-b117-11e8-9cc6-f5c16ee9cfd8.png) | ![nodeschool-losangeles](https://user-images.githubusercontent.com/579/45122159-ee966d00-b117-11e8-8319-44962f724ab9.png) | <img width="400" alt="screen shot 2018-09-05 at 2 21 29 pm" src="https://user-images.githubusercontent.com/579/45122378-7c725800-b118-11e8-8661-012eb30e79ad.png">

**Comment by terichadbourne** [comment]
Our new logo has been created and the source files can be found here: https://drive.google.com/drive/u/1/folders/1KT62AbG5lH6EVN7f8V_Cih-KBb7bR7Y3

(In the mock-ups of many versions, the one we've chosen is version 3.
