### ISSUE TITLE
Inconsistent references to IPFS or IPLD as place where objects are stored

### ISSUE THREAD

**Issue by terichadbourne** [ipfs-shipyard/proto.school#67]
Neither of the existing lesson series (basics and blog) explicitly define the difference between IPFS and IPLD. Because all of the commands refer to `ipfs` and some of the lessons explicitly state that you're putting objects into IPFS, that's what I first assumed was happening. However, I've found a number of references to IPLD throughout the lessons, given without an explanation of what that is and how it differs from IPFS. I don't know which are typos (though I believe at least one is) and which are intentional. This might be a sign that each lesson series had a different author. 

Questions for the team (@mikeal @olizilla @vmx  et al): 

- How should we introduce and define the difference between IPFS and IPLD in the lessons, briefly and in accessible language? 
- Will we say that objects are stored in IPFS or in IPLD? (Let's establish this now for future workshop authors.)  
- Which of the references below are correct as is and which need to be changed? 

I'm happy to make these edits once we have a consensus. 

_____________

BASICS - multiple references to IPFS, 1 to IPLD paths

Basics Lesson 1 (https://proto.school/#/basics/01)
Explainer box: `CID - Content Identifier. An unique address for a block of data in IPFS that is derived from it's content.`
No other mention of IPFS anywhere in this first lesson, but the page header says IPFS and the commands include `ipfs` so that's what I assume we're storing stuff in. 

Basics Lesson 2: (https://proto.school/#/basics/02)
`The way you express links in the ipfs DAG store is with an object.. `
`CID - Content Identifier. An unique address for a block of data in IPFS that is derived from it's content.`
`DAG - Directed Acyclic Graph. Blocks in IPFS form a graph as they can point to other blocks by their CID. These links can only point one direction (directed) and across the whole graph there are no loops or cycles (acyclic).`
`Put it into IPFS and return its CID.`
All signs point to IPFS. 

Basics Lesson 3 (https://proto.school/#/basics/03)
`ipfs.dag.get() allows queries using IPLD paths. These queries return an object containing the value of the query and any remaining path that was unresolved.`
This is the first ever mention of IPLD, and no context is given for why it's not IPFS being mentioned.

BLOG - no references to IPFS except that it's in the header and all the commands, many text references to IPLD as where things are being stored

Blog Lesson 1 (https://proto.school/#/blog/01)
`In the basic lessons, we learned that a link in IPLD is represented as an object with a slash as its only field...`
Note that IPLD is never explicitly referenced in the lesson this description links to (or anytime previous to it), so the user definitely didn't learn that there. :) 

Blog Lesson 2 (https://proto.school/#/blog/02)
`Everything that is stored in IPLD has an associated CID`
Previous references have said we're storing things in IPFS. 

Blog Lesson 3 (https://proto.school/#/blog/03)
`Insert those new tag objects into IPLD via ipld.dag.put() and return the two resulting CIDs as array.`
**I'm almost certain that `ipld.dag.put()` is a typo and meant to be `ipfs.dag.put()`, given what's in the code box here.** But again the text references putting things in IPLD, and it's elsewhere said IPFS while referring to the same command.

Blog Lesson 6 (https://proto.school/#/blog/06)
`We know the CID of a blog post as soon as it is stored in IPLD. We can use that CID to link from newer blog posts to older ones.`
Again, elsewhere we're told we're storing in IPFS.

**Comment by terichadbourne** [comment]
Quick update here: I pinged Matt & David about how they describe where the data is stored when you use `ipfs.dag.put()` and both responded with something roughly equivalent to "it's stored in IPFS as an IPLD object." That leads me to believe that anywhere that ProtoSchool says "stored in IPLD" it should be changed to say "stored in IPFS." 

I'd still love some feedback from @mikeal or @vmx on this in relation to the specific references to IPFS/ IPLD in these lessons (listed above) in case I'm missing some context.

**Comment by vmx** [comment]
IPFS and IPLD use the same storage mechanism: a repo (for JS that's https://github.com/ipfs/js-ipfs-repo/). In the ProtoSchool we use a general IPFS instance. The ipfs.dag.* commands are just forwarded to [js-ipld](https://github.com/ipld/js-ipld) which then does the work. Hence I'd say they are stored in IPLD, but as IPFS is also using IPLD it's also stored in IPFS.

**Comment by vmx** [comment]
I think the plan is to have workshops for all of IPFS. It just started IPLD centric as we did an IPLD workshop for the DWeb Summit.

**Comment by olizilla** [comment]
@terichadbourne yep, I wanted it to share the IPFS name and look and feel, and within it have workshops for all the things. We could dial down the IPFS branding and make it more generic if it feels jarring, but int general there should be IPFS specific workshops too, for things like the ipfs cli and ipfs http api.

What's there is just the content we could crank out in a couple of weeks.

**Comment by terichadbourne** [comment]
@mikeal Are there any places where you see IPLD mentioned (in the list I shared here) that I should _not_ change to IPFS, or is it all fair game? 

Shall I go ahead and change the logos at the left of the exercises to IPFS logos as well, since we won't be mentioning IPLD in them anymore?

**Comment by mikeal** [comment]
@terichadbourne yup, that sounds good :)

**Comment by terichadbourne** [comment]
Closed by #76
