### ISSUE TITLE
Naming proposal for units: workshop, lesson, exercise

### ISSUE THREAD

**Issue by terichadbourne** [ipfs-shipyard/proto.school#69]
I've noticed some variations in how we're all referring to the workshops and lessons on the ProtoSchool site, and it would be great to come to a consensus so we can use consistent wording both on the website and here in issues. There are three different things I can envision us needing names for: 

<img width="737" alt="lesson" src="https://user-images.githubusercontent.com/19171465/47655801-2e039780-db64-11e8-8d16-bd4a6683ae9d.png">
<img width="1042" alt="exercise" src="https://user-images.githubusercontent.com/19171465/47655811-32c84b80-db64-11e8-9e0d-7e2ba6a20f86.png">

I'm using my own proposed names as headers below: 

WORKSHOP. One is the top-level category. We describe ProtoSchool as a "collection of workshops" so I've been assuming that "Basics" and "Blog" are workshops (boxed in blue above). If one were to run one of these in a live event, workshop would feel like an appropriate name to me. However, I think some folks are calling these lessons. If we're calling them something other than workshops, the paragraph at the top of the homepage should be changed to match. 

LESSON. The next level down is what I think of as lessons (circled in red above). A series of them makes up the thing above that I think of as a workshop. However, on the main page these are labelled as exercises. I'd argue that since we're about to add a new workshop where you only read, rather than code, to learn, exercise is not an appropriate name, and that the main page should list these as lessons, not exercises. 

EXERCISE. The third thing, which may or may not need a public-facing name, is the box where you type in code (circled in purple), which to me feels like an exercise, and is called that in our code structure. Moving forward, once we add the workshop on decentralized data structures, some lessons will have these and some won't.  Right now, this box is labelled as exercise. Unless we plan to have multiple of these in a single lesson, which I don't think we should, it could be argued that we might want to remove this label to avoid the following problem: If we have a workshop with 5 lessons but only the 2nd and 4th have exercises in them, are those exercises 2 and 4 (despite 1, 3, and 5 not existing) or are they exercises 1 (confusingly delivered in lesson 2) and 2 .(confusingly delivered in lesson 4).  If there's only going to be 1 per lesson, we could either label these boxes just "Exercise" or give them no header, rather than referencing an exercise number.

@mikeal et al, I'd love your opinions on this naming proposal so I can then update the site accordingly.

**Comment by mikeal** [comment]
I'm +1 on these names.

Also, looking at the names of the lessons and exercises, we could use some iteration because these aren't very inviting :)

**Comment by terichadbourne** [comment]
How would you feel about lesson names that put the user perspective more in focus by describing lessons as actions rather than nouns? For example, "Basic linking" might be "Create a link."

Action items here are: 
- [ ] Change "Exercise X" to "Lesson X" on the homepage.
- [ ] Change "Exercise X" to just "Exercise" in the exercise boxes
- [ ] Review lesson names to make them more inviting

**Comment by terichadbourne** [comment]
Closed by pr #76
