### ISSUE TITLE
Move to ipfs-shipyard org

### ISSUE THREAD

**Issue by diasdavid** [ipfs-shipyard/proto.school#7]
@mikeal can we get this moved to the IPFS?

**Comment by mikeal** [comment]
Sure, but I thought we were going to hold off until after dweb to discuss potentially building out a new org and a community around the workshops?

Also, I need to get added to ipfs-shipyard org in order to transfer :)

**Comment by olizilla** [comment]
yes please can haz. I just forked the repo like an animal.

**Comment by diasdavid** [comment]
It's definitely part of the plan to consider creating a org just for community development stuff. For now, it is a missed opportunity to point people to a repo to be part of the community that is not within the orgs of the community already.

Adding to that, we already have good practices of managing permissions, our own CI and so on, which makes it easier for everyone to contribute.

**Comment by mikeal** [comment]
Cool, I'll transfer the repo after our test run later today. I don't want to do it before because I'm pretty sure it's going to break the auto-deploy and I'd like that to be functional while we're doing the test run.

**Comment by mikeal** [comment]
Moved the repo. CI still seems to work and auto-deploy to gh-pages but the website is still showing the old page. It's either because the DNS change still need to propagate or there's some caching in ghpages that needs to expire.

**Comment by terichadbourne** [comment]
@mikeal Should this issue be marked as closed? I believe it's related to #51 (about how community members magically get their own GH pages) but I don't entirely understand the implications of how the org and repo names we choose for ProtoSchool will affect the URLs that community groups end up with.

**Comment by mikeal** [comment]
This can be closed. The other issue is actually to move this, again, to its **own** org :)
