### ISSUE TITLE
Display workshop title and progress bar on each lesson page 

### ISSUE THREAD

**Issue by terichadbourne** [ipfs-shipyard/proto.school#70]
Currently, on each individual lesson page, we only indicate the name of the lesson the person is working on (that lesson name being occasionally duplicated across multiple workshops). I personally would find it helpful to also see which workshop I'm in (eg Basics or Blog) and how far along I am in (eg Lesson 2 of 5). We could do this purely in text or with some sort of progress bar. 

If we did a progress bar, I'm envisioning x small boxes (where x is the total number of lessons in the workshop), of which the ones you've completed are colored, the one you're on is colored in the same circle but also has a border, and the upcoming ones are gray. (Very open to styling suggestions here.) At the moment, we don't track what lessons have actually been completed, so for styling purposes this would just presume you've completed the ones prior to the one you're looking at.  

Any thoughts @mikeal @olizilla et al?

**Comment by olizilla** [comment]
Very much in favour. We need to do the plumbing to store your progress anyway. Right now you follow links and everything is stateless... we don't track that you are actually completing the lessons in order, and all your work is lost as soon as you navigte away from a lesson. It would be valuable to be able to refer back to your answers!

**Comment by mikeal** [comment]
Love it!

**Comment by terichadbourne** [comment]
It sounds like storing actual progress and responses is a bigger challenge which can be separated from the UI changes I'm proposing here. That's keep that task separate, under issue #13. 

For displaying how far you are along within the workshop, do we have a preference between the following approaches?  
(a) "Lesson 2 of 5" with no progress bar 
(b) "Lesson 2 of 5" plus a progress bar with no numbers on it 
(c) A progress bar with no numbers on it (you'd count the boxes if you care about your lesson number or the total number of lessons in the workshop) 
(d) A progress bar as I described originally but with a number in each box 

For this issue, we'll need to: 
- [ ] Add the workshop name to the lesson page
- [ ] Display progress (still debating format for this)
