### ISSUE TITLE
Place logo on site

### ISSUE THREAD

**Issue by terichadbourne** [ipfs-shipyard/proto.school#78]
@mikeal @olizilla 
Do we need the IPFS logo on the ProtoSchool header, or can it be removed? 
How do you feel about the following options? 

If I substitute the real ProtoSchool logo for the pseudo-logo but leave the IPFS logo above it we get **OPTION A**: 
![image](https://user-images.githubusercontent.com/19171465/47920884-9cf52f00-de89-11e8-8b15-18f2769dc8a3.png)

Removing the IPFS logo so the branding is for ProtoSchool (but with IPFS mentioned in the blurb describing ProtoSchool) we get **OPTION B**, which I prefer. (Note that I've been frequently clicking that IPFS logo thinking it will take me to the IPFS website, which it doesn't.) 
![image](https://user-images.githubusercontent.com/19171465/47921097-24db3900-de8a-11e8-923e-a527ba405d38.png)

As a potential **OPTION C**, I could ask Agata to make us a version of the logo with the tagline included and alignment fixed, that would look roughly like this: 
![image](https://user-images.githubusercontent.com/19171465/47921650-7fc16000-de8b-11e8-9e0d-fd30087b5c52.png)

I think I'd find Option C most visually appealing if it were a designer making the logo instead of me cutting and pasting in Preview. :) 

For my own reference, option (a) is temporarily made like so: 

```
<div class="flex-none">
        <div class="ph2 ph4-ns">
          <img src="./ipfs-logo.svg" alt="IPFS" style="height: 66px" />
        </div>
        <div style="padding-left: 82px">
          <img src="./ps_logo_white_horizontal.svg" alt="ProtoSchool" style="height: 100px"/>
        </div>
        <div class="header-text indent-1">
          <h2 class="ma0 fw5">
            The interactive IPFS protocol workshop
          </h2>
        </div>
      </div>
```

**Comment by mikeal** [comment]
The "top level branding" and like the corner logo should move to be "ProtoSchool."

**Comment by terichadbourne** [comment]
Sorry, @mikeal, I don't understand what you're proposing. Are you asking me to make the site look like it did before (with PROTOSCHOOL as fancy text above the tagline) and put the ProtoSchool logo where the IPFS logo was at top left?

**Comment by mikeal** [comment]
Replacing the top IPFS logo with the ProtoSchool logo.

**Comment by terichadbourne** [comment]
@mikeal Do you mean replacing the small logo at top left but leaving ProtoSchool as text rather than replacing it with the bigger logo, like so? 

![image](https://user-images.githubusercontent.com/19171465/48226482-e8b64580-e36d-11e8-88d0-99f6e1b13630.png)

**Comment by mikeal** [comment]
I see now. It's a little redundant with both saying "ProtoSchool."

Maybe we can cut the text based "PROTOSCHOOL" and just put the tagline there. Also, maybe we can get a new tagline :)

**Comment by terichadbourne** [comment]
If we're not using the words, I'd rather see a bigger version of the logo so a tagline isn't outweighing the name of the site. (And then obviously not duplicating the logo by putting a smaller version of it in the top left.)  Option C is my favorite aesthetically of the ones in my first message above, though it would require some help from Agata. If we did that we'd need to confirm our tagline before asking her to spend her time on it. Do you already have a new tagline in mind @mikeal?
